from app.models import CatalogItem

CATALOG = [
    CatalogItem(
        id="kaggle-worcap",
        institution="Kaggle / WORCAP 2026",
        region="international",
        role="Fonte oficial dos arquivos de treino, teste e submissão do desafio.",
        requirement="required",
        access="Requer conta, aceite das regras e credencial individual.",
        documentation_url="https://www.kaggle.com/docs/api",
    ),
    CatalogItem(
        id="era5-cds",
        institution="ECMWF Copernicus Climate Data Store",
        region="international",
        role="Reanálise ERA5 para reprodução e enriquecimento controlado.",
        requirement="extra",
        access="Requer cadastro, aceite dos termos do dataset e CDS API.",
        documentation_url="https://cds.climate.copernicus.eu/how-to-api",
    ),
    CatalogItem(
        id="nasa-power",
        institution="NASA POWER",
        region="international",
        role="Séries meteorológicas mensais pontuais ou regionais para comparação.",
        requirement="extra",
        access="API pública; respeitar limites e resolução de origem.",
        documentation_url="https://power.larc.nasa.gov/docs/services/api/temporal/monthly/",
        enabled=True,
    ),
    CatalogItem(
        id="noaa-psl-oni",
        institution="NOAA Physical Sciences Laboratory",
        region="international",
        role="Índice ONI observado para contexto ENSO.",
        requirement="extra",
        access="Arquivo público; validar periodicidade e versão antes de usar.",
        documentation_url="https://psl.noaa.gov/data/correlation/oni.data",
    ),
    CatalogItem(
        id="inmet",
        institution="INMET",
        region="national",
        role="Observações de estações e validação de contexto no Brasil.",
        requirement="extra",
        access="Acesso à API deve ser solicitado ao INMET pelo canal oficial.",
        documentation_url="https://portal.inmet.gov.br/fale-conosco",
    ),
    CatalogItem(
        id="inpe-cptec",
        institution="INPE / CPTEC",
        region="national",
        role="Produtos meteorológicos nacionais para contexto e comparação.",
        requirement="extra",
        access="Definir produto e política de acesso antes de implementar adaptador.",
        documentation_url="https://www.cptec.inpe.br/",
    ),
]
