from app.models import CatalogItem

CATALOG = [
    CatalogItem(
        id="open-meteo",
        institution="Open-Meteo",
        region="international",
        role="Condições atuais e previsão de sete dias com modelos globais recentes.",
        requirement="extra",
        access="API pública sem chave para uso não comercial, com atribuição.",
        documentation_url="https://open-meteo.com/en/docs",
        enabled=True,
    ),
    CatalogItem(
        id="cams",
        institution="Copernicus Atmosphere Monitoring Service (CAMS)",
        region="international",
        role="Qualidade do ar, material particulado, gases e índice UV.",
        requirement="extra",
        access="Disponibilizado pelo endpoint Air Quality do Open-Meteo, com atribuição.",
        documentation_url="https://open-meteo.com/en/docs/air-quality-api",
        enabled=True,
    ),
    CatalogItem(
        id="official-challenge-dataset",
        institution="Dataset científico oficial",
        region="international",
        role="Fonte oficial dos arquivos de treino, teste e exportação final.",
        requirement="required",
        access="Requer conta, aceite das regras e credencial individual.",
        documentation_url="https://github.com/SouBeatrizKaroline/Climazoide-Backend#dados-utilizados",
    ),
    CatalogItem(
        id="era5-cds",
        institution="ECMWF Copernicus Climate Data Store",
        region="international",
        role="Reanálise ERA5 para reprodução e enriquecimento controlado.",
        requirement="extra",
        access="Requer cadastro, aceite dos termos do dataset e CDS API.",
        documentation_url="https://cds.climate.copernicus.eu/how-to-api",
    ),
    CatalogItem(
        id="nasa-power",
        institution="NASA POWER",
        region="international",
        role="Séries meteorológicas mensais pontuais ou regionais para comparação.",
        requirement="extra",
        access="API pública; respeitar limites e resolução de origem.",
        documentation_url="https://power.larc.nasa.gov/docs/services/api/temporal/monthly/",
        enabled=True,
    ),
    CatalogItem(
        id="noaa-cpc-oni",
        institution="NOAA Climate Prediction Center",
        region="international",
        role="Índice ONI observado para contexto ENSO.",
        requirement="extra",
        access="Arquivo público; validar periodicidade e versão antes de usar.",
        documentation_url="https://www.cpc.ncep.noaa.gov/data/indices/oni.ascii.txt",
        enabled=True,
    ),
    CatalogItem(
        id="usno-astronomy",
        institution="US Naval Observatory",
        region="international",
        role="Fase e iluminação lunar, nascer e pôr do Sol.",
        requirement="extra",
        access="API pública sem chave.",
        documentation_url="https://aa.usno.navy.mil/data/api",
        enabled=True,
    ),
    CatalogItem(
        id="inmet",
        institution="INMET",
        region="national",
        role="Observações de estações e validação de contexto no Brasil.",
        requirement="extra",
        access="Acesso à API deve ser solicitado ao INMET pelo canal oficial.",
        documentation_url="https://portal.inmet.gov.br/fale-conosco",
    ),
    CatalogItem(
        id="inpe-cptec",
        institution="INPE / CPTEC",
        region="national",
        role="Produtos meteorológicos nacionais para contexto e comparação.",
        requirement="extra",
        access="Serviço XML público; a disponibilidade é reportada em cada consulta.",
        documentation_url="https://servicos.cptec.inpe.br/XML/",
        enabled=True,
    ),
]
